[DSD-1847] Added mock-mv in Readme and install all scripts.
mosip/mosip-infra pull request #1198
Opened 2022-12-21 13:12 UTC by akilalakshmanan

2022-12-21 13:54 UTC, syedsalman3753 requested changes

2022-12-21 13:54 UTC, syedsalman3753 commented on deployment/v3/mosip/README.md
> +* [Mock MV](mock-mv)
link it mock-mv README.md file (mock-mv/README.md)

also, check if README.md exists for mock-mv. 
if not add it

2022-12-21 13:54 UTC, syedsalman3753 commented on deployment/v3/mosip/mock-mv/README.md
> +Mock MV reads request from queue and mocks response for external "manual adjudication" and "verification" systems. Mock MV runs inside the cluster as a Kubernetes pod.
please update from below description
````
Mock MV reads the request from the queue and mocks the response for external "manual adjudication" and "verification" systems. Mock MV runs inside the cluster as a Kubernetes pod.
```

2022-12-21 14:04 UTC, syedsalman3753 approved these changes

2022-12-22 03:53 UTC, ckm007 commented on deployment/v3/mosip/mock-mv/README.md
> +Mock MV reads the request from the queue and mocks the response for external "manual adjudication" and "verification" systems. Mock MV runs inside the cluster as a Kubernetes pod.
Mock MV is the mock implementation of manual adjudication or varification system. Mock MV is a microservice installed inside Mosip K8 cluster.

Please update the same in introduction.

2022-12-22 05:06 UTC, ckm007 approved these changes

2022-12-22 05:06 UTC, merged