DSD-2602 created script files for bqat
mosip/mosip-infra pull request #1321
Opened 2023-05-29 09:29 UTC by bhumi46

2023-05-29 12:07 UTC, ckm007 commented on deployment/v3/mosip/bqatsdk/install.sh
> +CHART_VERSION=12.0.2
version update required

2023-05-29 14:21 UTC, syedsalman3753 requested changes

2023-05-29 14:21 UTC, syedsalman3753 commented on deployment/v3/mosip/bqatsdk/values.yaml
> +  bioapiImpl: io.bqat.sdk.services.impl.BqatQualitySdkService
Please remove values.yaml as the same values has been added to helm charts values.yaml

2023-05-29 14:21 UTC, syedsalman3753 commented on deployment/v3/mosip/bqatsdk/install.sh
> +  helm -n $NS install bqat-sdk mosip/bqat-sdk -f values.yaml --version $CHART_VERSION
please remove "f values.yaml" as it is not required here

2023-05-29 14:35 UTC, syedsalman3753 requested changes
can you please tell me y values.yaml has been added to this. As in helm chart we have provided the urls.

2023-05-29 14:35 UTC, syedsalman3753 commented on deployment/v3/mosip/bqatsdk/README.md
> +* Update `values.yaml` with your bqatsdk zipped library url and classpath.
remove this point

2023-05-30 05:23 UTC, syedsalman3753 commented
@bhumi46 please remove last 3 commits

2023-05-30 05:53 UTC, syedsalman3753 approved these changes

2023-05-31 12:29 UTC, syedsalman3753 requested changes
Added the service in all/install-all.sh.

make sure to be in sequence you can check with @ckm007

2023-06-01 12:16 UTC, merged