[DSD-2623]Updating idacert.md
mosip/mosip-infra pull request #1322
Opened 2023-05-30 06:03 UTC by Mahesh-Binayak

2023-05-30 11:26 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +- For IDA we have two kinds of certificate exchange.
In IDA, there are two kinds of certificate exchange.

2023-05-30 11:26 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +	  A) IDA Zero-knowledge certificate exchange.
1. IDA Zero-knowledge certificate exchange

2023-05-30 11:27 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +	  B) IDA mpartner-default-auth partner certificate exchange.
2. IDA mpartner-default-auth partner certificate exchange

2023-05-30 11:28 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> + A) For IDA Zero-Knowledge certificate exchange,below are the steps
For IDA Zero-Knowledge certificate exchange, below are the steps:

2023-05-30 11:36 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  * 2. Get the certificate data from the below URL.The used application id = IDA ad reference id =CRED_SERVICE
Get the certificate data from the URL mentioned below. The application id used is IDA and reference id =CRED_SERVICE 

(Please check if application id has and underscore and the same for reference id)

2023-05-30 11:36 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +       make sure to copy the certificate value in the response from the above request.
Ensure  to copy the certificate value in the response from the above request.

2023-05-30 11:37 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  B)for IDA mpartner-default-auth partner certificate exchange, below are the steps
For IDA mpartner-default-auth partner certificate exchange, below are the steps:

2023-05-30 11:39 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  * 2. Get the certificate data from the below URL.The used application id = IDA ad reference id =CRED_SERVICE
I see it written as appId below... so, we can mention Application ID (appId) for clarity

2023-05-30 11:39 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +       make sure to copy the certificate value in the response from the above request.
Ensure to copy the certificate value in the response from the above request.

(leave a space in between sentences)

2023-05-30 11:41 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +## This concludes the required certificate exchange for IDA.
## not required in the above sentence.

2023-05-30 11:42 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
>  # Troubleshooting
Troubleshooting to have ## or ### (not a page title)

2023-05-30 11:42 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  make sure to copy certificate value in the response. This is  MOSIP's pms-signed certificate.
Make sure....

2023-05-30 11:42 UTC, SwatiPeriwal requested changes
Please go through the comments and update accordingly

2023-05-30 12:14 UTC, Mahesh-Binayak commented
> Please go through the comments and update accordingly

sure @SwatiPeriwal , Thanks for the update

2023-05-30 13:11 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +- In IDA, there are two kinds of certificate exchange.
This should end with a colon(:) and not full stop

2023-05-30 13:11 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +	  1 . IDA Zero-knowledge certificate exchange
No need of space after 1 -- 1. IDA Zero-knowledge certificate exchange

2023-05-30 13:11 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +	  2 . IDA mpartner-default-auth partner certificate exchange.
Extra space after 2

2023-05-30 13:12 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +	  2 . IDA mpartner-default-auth partner certificate exchange.
Full stop not required here

2023-05-30 13:13 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  * 1. Authenticate yourself and get authorization token from authmanager swagger
Can add full stop at the end of the sentence

2023-05-30 13:13 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  * 2. Get the certificate data from the URL mentioned below. The application id(appId) used is IDA and reference id(refId) =CRED_SERVICE
reference id(refId)= CRED_SERVICE

2023-05-30 13:14 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +For IDA mpartner-default-auth partner certificate exchange, below are the steps
add : after steps

2023-05-30 13:14 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +   * 1. Authenticate yourself and get authorization token from authmanager swagger
Add full stop

2023-05-30 13:16 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  * 5. Upload copied IDA certificate from the above request in the below SWAGGER URL :-
colon (:) is sufficient at the end

2023-05-30 13:16 UTC, SwatiPeriwal commented on deployment/sandbox-v2/docs/idacert.md
> +  * 7. Upload mpartner-default-auth Partner certificate in the below SWAGGER URL:-
: towards end

2023-05-31 04:24 UTC, SwatiPeriwal approved these changes
Reviewed and approving doc changes

2023-06-07 03:20 UTC, ckm007 approved these changes

2023-06-08 04:47 UTC, merged