[MOSIP-27961] Updated README.md to backup and restore kafka & softhsm
mosip/mosip-infra pull request #1333
Opened 2023-06-12 10:40 UTC by syedsalman3753

2023-06-13 06:16 UTC, SwatiPeriwal commented on deployment/v3/external/hsm/softhsm/README.md
> +## Backup softhsm
## Backup SoftHSM

2023-06-13 06:16 UTC, SwatiPeriwal commented on deployment/v3/external/hsm/softhsm/README.md
> +* Update below variable
Update the below variables

2023-06-13 06:17 UTC, SwatiPeriwal commented on deployment/v3/external/hsm/softhsm/README.md
> +* Update the variable provided below.
variables

2023-06-13 06:18 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +## Procedure to Backup & Restore bitnami kafka via Velero
Procedure to Backup & Restore Bitnami Kafka via Velero

2023-06-13 06:20 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Required separate `minio` server / 'S3' , accessible from both backup & restore clusters along with `api` & `console` port accessible.
Require separate `minio` server / `S3`, accessible from both backup & restore clusters along with accessible `api` & `console` port.

2023-06-13 06:22 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Login to the console machine,navigate to the `Kafka directory (under /v3/external/)`, and execute the backup script to create a backup of Kafka.
Login to the console machine, navigate to..............

Space after comma needs to be added in the above sentence

2023-06-13 06:22 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Login to the console machine,navigate to the `Kafka directory (under /v3/external/)`, and execute the backup script to create a backup of Kafka.
Add space after comma

2023-06-13 06:23 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +#### Restore kafka
Restore Kafka

2023-06-13 06:28 UTC, SwatiPeriwal requested changes
Minor changes

2023-06-13 10:44 UTC, SwatiPeriwal commented on deployment/v3/external/object-store/minio/README.md
> +  mc: <ERROR> Unable to list folder. The request signature we calculated does not match the signature you provided. Check your key and signing method
Add full stop

2023-06-13 10:44 UTC, SwatiPeriwal commented on deployment/v3/external/object-store/minio/README.md
> +  Then, Ensure that you provide the appropriate API version, either `--api S3v2` or `--api S3v4`, when executing the `mc set alias` command.
No capitals for ensure here

2023-06-13 17:51 UTC, ckm007 commented on deployment/v3/external/hsm/softhsm/README.md
> +  export POD_NAME=<pod-name>
softhsm pod name

2023-06-13 17:52 UTC, ckm007 commented on deployment/v3/external/hsm/softhsm/README.md
> +  export POD_NAME=<pod-name>
<destination softhsm pod name>

2023-06-14 07:08 UTC, ckm007 commented on deployment/v3/external/hsm/softhsm/README.md
> +  export POD_NAME=<pod-name>
<softhsm source pod name>

2023-06-14 07:08 UTC, ckm007 commented on deployment/v3/external/hsm/softhsm/README.md
> +  export POD_NAME=<pod-name>
softhsm source pod name

2023-06-14 07:09 UTC, ckm007 commented on deployment/v3/external/hsm/softhsm/README.md
> +  export POD_NAME=<pod-name>
softhsm destination pod name

2023-06-14 07:16 UTC, ckm007 commented
add section for removal of new keys from softhsm before colpying backed up keys.

2023-06-14 09:03 UTC, merged