[MOSIP-27549] added error handling in copy_cm.sh and copy_secrets.sh …
mosip/mosip-infra pull request #1357
Opened 2023-07-04 12:14 UTC by Rakshithb1

…scripts

2023-07-06 18:50 UTC, ckm007 requested changes
Can we add funtions the similiar way we have made changes in all our install scripts.
e.g. https://github.com/mosip/mosip-infra/blob/release-1.2.0.1/deployment/v3/mosip/biosdk/install.sh

2023-07-11 05:15 UTC, ckm007 commented on deployment/v3/mosip/admin/copy_cm.sh
> +function coping_cm() {
its copying not coping.

2023-07-11 05:22 UTC, Rakshithb1 commented on deployment/v3/mosip/admin/copy_cm.sh
> +function coping_cm() {
updated to copying

2023-07-11 06:55 UTC, ckm007 approved these changes

2023-07-11 06:55 UTC, merged