[DSD-3091]added delete.sh for msg-gateways
mosip/mosip-infra pull request #1375
Opened 2023-07-20 15:43 UTC by Rakshitha650

2023-07-20 16:29 UTC, syedsalman3753 requested changes

2023-07-20 16:29 UTC, syedsalman3753 commented on deployment/v3/external/msg-gateway/delete.sh
> +          kubectl -n $NS delete --ignore-not-found=true configmap msg-gateway
Add helm uninstall instead of kubectl command

2023-07-21 06:49 UTC, syedsalman3753 approved these changes

2023-07-21 08:07 UTC, ckm007 approved these changes

2023-07-21 08:07 UTC, merged