[MOSIP-28215] Added steps to backup/restore kafka README.md
mosip/mosip-infra pull request #1425
Opened 2023-09-20 10:09 UTC by syedsalman3753

2023-09-21 05:14 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +## Procedure to Backup & Restore Bitnami Kafka via Manually
## Steps to Backup & Restore Bitnami Kafka manually

2023-09-21 05:15 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Zip & Unzip packages to installed on both backup/restore
This sentence is not meaningful... please check...

2023-09-21 05:16 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Set websub and Kafka replicas to zero via the below command.
Set WebSub and Kafka replicas to zero via the below command.

2023-09-21 05:17 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Once websub & kafka pod are completely terminated, Goto `/srv/nfs/mosip/`.
Once Websub & Kafka pods are completely terminated, go to `/srv/nfs/mosip/`.

2023-09-21 05:25 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Move the backup file to the machine where the restore cluster.
ove the backup file to the machine where the restore cluster is present.

2023-09-21 05:35 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Wait till all changes applied & pods are up and running.
Wait until all changes are applied and the pods are up and running.

2023-09-21 05:35 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Update N value (i.e., number of replicas ) in the below command, to clear the data.
To clear the data, update N value (i.e., number of replicas) in the below command.

2023-09-21 05:36 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Update N value (i.e., number of replicas ) in the below command, to copy data from backup.
To copy data from backup, update N value (i.e., number of replicas) in the below command.

2023-09-21 05:37 UTC, SwatiPeriwal requested changes
Please make the necessary corrections

2023-09-21 16:44 UTC, SwatiPeriwal commented on deployment/v3/external/kafka/README.md
> +* Once all kafka services are up, confirm the existence of topics, messages, etc... via kafka-ui.
Once all the kafka services are up, confirm the existence of topics, messages, etc., via the kafka-ui.

2023-09-21 16:44 UTC, SwatiPeriwal approved these changes
Approved

2023-09-22 03:05 UTC, ckm007 commented on deployment/v3/external/kafka/README.md
> +  kc2 -n default scale --replicas=0 deploy consolidator-websub-service websub-service
use kubectl with namespace and kubeconfig.
This is because this is a generic process for backup. 
Or please define here what is kc2.

2023-09-22 03:06 UTC, ckm007 commented on deployment/v3/external/kafka/README.md
> +  kc2 -n default scale --replicas= deploy consolidator-websub-service websub-service
Since we had stopped websub and then starting the same now, lets add a line to restart all the websub dependent services.

2023-09-25 09:32 UTC, ckm007 commented on deployment/v3/external/kafka/README.md
> +* Set WebSub and Kafka replicas to zero via the below command.
Set WebSub and Kafka replicas to zero for V2 based existing env use below command.

2023-09-25 11:31 UTC, ckm007 approved these changes

2023-09-25 11:31 UTC, merged