[MOSIP-29035] Updated resident oidc secret name
mosip/mosip-infra pull request #1430
Opened 2023-09-26 10:22 UTC by akilalakshmanan

2023-09-27 10:12 UTC, syedsalman3753 requested changes

2023-09-27 10:12 UTC, syedsalman3753 commented on deployment/v3/mosip/resident/install.sh
> +  kubectl create secret generic resident-oidc-onboarder-key -n $NS --from-literal=resident-oidc-clientid= --dry-run=client -o yaml | kubectl apply -f -
please add single quotes ''

2023-09-27 11:34 UTC, syedsalman3753 approved these changes

2023-10-04 06:06 UTC, ckm007 approved these changes

2023-10-04 06:06 UTC, merged