[MOSIP-29979] updated table info in values.yaml
mosip/mosip-infra pull request #1462
Opened 2023-12-21 07:29 UTC by bhumi46

2023-12-21 08:22 UTC, syedsalman3753 requested changes
* Take table info as dictionary not as a list

For example:

 tables_info:
&nbsp;   resident_archive_table_info:
&nbsp;&nbsp;      source_table: "abis_response_det"
&nbsp;&nbsp;      xxxxxx
&nbsp;&nbsp;      need_archival: "archive"
&nbsp   esignet_archive_table_info:
&nbsp;&nbsp;      source_table: "abis_response_det"
&nbsp;&nbsp;      archive_table: "mosip_regprc_abis_response_det"
&nbsp;&nbsp;      id_column: "abis_resp_id"
 &nbsp;&nbsp;     date_column: "cr_dtimes"
&nbsp;&nbsp;      retension_days: 183
&nbsp;&nbsp;      operation_type: "archive"

2023-12-27 09:20 UTC, syedsalman3753 approved these changes

2023-12-27 11:02 UTC, ckm007 reviewed
Can you add a Readme for required imp key and its values.

2023-12-28 10:54 UTC, ckm007 approved these changes

2023-12-28 10:54 UTC, merged