[DSD-4272] Install.sh script for Credentialfeeder
mosip/mosip-infra pull request #1485
Opened 2024-01-25 07:05 UTC by VSIVAKALYAN

2024-01-29 04:40 UTC, syedsalman3753 requested changes

2024-01-29 04:40 UTC, syedsalman3753 commented on deployment/v3/mosip/credential-feeder/install.sh
> +CHART_VERSION=12.0.2
In the helm chart, the chart version is set to 1.0.0. 

please get it confirmed by @ckm007

2024-01-29 04:40 UTC, syedsalman3753 commented on deployment/v3/mosip/credential-feeder/install.sh
> +  helm repo update
helm repo add mosip is missing please add

2024-01-31 04:43 UTC, syedsalman3753 requested changes

2024-01-31 04:43 UTC, syedsalman3753 commented on deployment/v3/mosip/credential-feeder/install.sh
> +
helm repo update

2024-01-31 04:44 UTC, syedsalman3753 requested changes

2024-01-31 04:44 UTC, syedsalman3753 commented on deployment/v3/mosip/credential-feeder/install.sh
> +  helm repo update
please review this

2024-01-31 04:52 UTC, syedsalman3753 approved these changes

2024-01-31 05:35 UTC, ckm007 commented
please resolve coversations once it is fulfilled.

2024-01-31 05:36 UTC, merged