[MOSIP-31733] Ethiopian property migration bugs fixed for platform up…
mosip/mosip-infra pull request #1520
Opened 2024-03-18 10:47 UTC by Mohanraj209

…grade.

2024-03-20 06:23 UTC, gsasikumar requested changes

2024-03-20 08:10 UTC, Mohanraj209 commented on deployment/v3/utils/prop_migrator/Overview.md
> +This script automates the process of comparing and updating configurations between an existing old configuration branch and a latest configuration branch. It helps ensure that the latest configuratio
Migrator script compares the property files from one version of config to another version, while performing the upgrade of v2 version to v3 we knew that v2 environments were using 1.1.5.5 config branch and v3 environments were using 1.2.0.1 so we compared these config branches using migrator and listed out the differences. so here the old configuration branch will be "1.1.5.5" and latest configuration branch will be '1.2.0.1'.

2024-03-20 08:10 UTC, Mohanraj209 commented on deployment/v3/utils/prop_migrator/Overview.md
> +The script compares property files between an old config branch and a latest config branch, identifies the differences, and generates CSV files to summarize the results, then automates the process of
Migrator script compares the property files from one version of config to another version, while performing the upgrade of v2 version to v3 we knew that v2 environments were using 1.1.5.5 config branch and v3 environments were using 1.2.0.1 so we compared these config branches using migrator and listed out the differences. so here the old configuration branch will be "1.1.5.5" and latest configuration branch will be '1.2.0.1'.

2024-03-20 08:14 UTC, Mohanraj209 commented on deployment/v3/mosip/conf-secrets/README.md
> +Note: The conf-secrets must not be deleted in any case of re-deployment, upgrade or migration process as we have separated the conf-secrets from config-server to ensure conf-secrets are not deleted.
@gsasikumar yes it is possible to take backup of conf-secrets and restore, this is just a precautionary message to the users to not delete conf-secrets without any backup.

2024-03-25 10:03 UTC, gsasikumar commented on deployment/v3/mosip/conf-secrets/README.md
> +Note: The conf-secrets must not be deleted in any case of re-deployment, upgrade or migration process as we have separated the conf-secrets from config-server to ensure conf-secrets are not deleted.
Can you raise a task for back up so we can consider this as resolved?

2024-03-25 10:04 UTC, gsasikumar commented on deployment/v3/utils/prop_migrator/Overview.md
> +This script automates the process of comparing and updating configurations between an existing old configuration branch and a latest configuration branch. It helps ensure that the latest configuratio
Can we make this sentence better to reflect the above clearly?

2024-03-25 10:16 UTC, Mohanraj209 commented on deployment/v3/mosip/conf-secrets/README.md
> +Note: The conf-secrets must not be deleted in any case of re-deployment, upgrade or migration process as we have separated the conf-secrets from config-server to ensure conf-secrets are not deleted.
sure @gsasikumar

2024-03-25 12:16 UTC, Mohanraj209 commented on deployment/v3/mosip/conf-secrets/README.md
> +Note: The conf-secrets must not be deleted in any case of re-deployment, upgrade or migration process as we have separated the conf-secrets from config-server to ensure conf-secrets are not deleted.
created task for the above https://mosip.atlassian.net/browse/MOSIP-32082

2024-03-25 13:05 UTC, gsasikumar approved these changes

2024-03-25 13:05 UTC, merged